### PR TITLE
Add config option to set current working directory to Service & wrapper.js

### PR DESCRIPTION
**Pull request by matthewadams**
There was no option to set the current working directory of the forked process.  I had trouble getting my service to run because node was trying to resolve required modules at **C:\Windows\system32\**node_modules\...

Even though I think a reasonable default for cwd should be the directory containing the launched script, I kept the current behavior of setting no explicit cwd.

PS:  it looks like there were some line ending issues in lib/wrapper.js.  I hope they're fixed with this commit.  I added a .gitattributes in case folks don't have theirs set globally.

PPS:  I also added a .gitignore.

### CODE REVIEW

**Comment by matthewadams** [comment]
FYI, the only substantive change to lib/wrapper.js was to insert
```
      .alias('d','cwd')
      .describe('cwd','The absolute path of the current working directory of the script to be run as a process.')
      .check(function(argv){
        require('fs').existsSync(p.resolve(argv.d),function(exists){
          return exists;
        });
      })
```
beginning at line 15.

**Comment by matthewadams** [comment]
Looks good to go, AFAICT.

**Comment by matthewadams** [comment]
Sweet.  Thanks for merging.  We're going to production within a few weeks.  Is it possible to do a release that includes this enhancement in that time?  Please advise.

**Comment by coreybutler** [comment]
It's already been published to npm as v0.1.9.

**Comment by matthewadams** [comment]
Math.pow(Sweet,2)!  :)

**Pull request merged**
