### PR TITLE
Remove optimist in favor of @author.io/arg

### PR DESCRIPTION
**Pull request by forty**
This avoids a security issue on minimist, which is an indirect dependency

### CODE REVIEW

**Comment by forty** [comment]
Disclaimer: this was all done manually and I haven't tested anything :) please review with great care

**Comment by aksswami** [comment]
@coreybutler possible to merge this anytime soon?

**Comment by JyotsnaC** [comment]
Looking for the same. Issue to be resolved.

**Comment by DFG-kjtroll** [comment]
Looking to deploy my express API with this, and my infrastructure guys will love to see a clean ` npm audit ` before global install... my current workaround is to force it to use minimist 0.2.1 using npm-force-resolutions. But that only patches a project install of node-windows and I'm not sure if it introduces bugs... Would love to see this merged!

**Pull request merged**
