### PR TITLE
Feature/allow command arguments

### PR DESCRIPTION
**Pull request by julianhille**
Add possibility to add arguments to the script to be called

### CODE REVIEW

**Comment by jdziat** [comment]
Thanks for the PR,

I believe the intention is to keep the api calls identical across the three OS packages though. Any additional configuration or specific functionality should be left to to the developer to add via a wrapper or some other means.

**Comment by julianhille** [comment]
That is why I added a pr to add arguments for all the three packages.

**Comment by jdziat** [comment]
My apologies should of checked the PRs on those. So we need consensus across all three repos.

Also can you provide use cases where a flags property would benefit over the methods I purposed. The only one I can think of is modifying the service outside of these packages. However it is very early for me so I may not be thinking clearly.

**Comment by julianhille** [comment]
I've got a single app compiled / packaged which needs some command line args to start as a service.

**Pull request closed without merging**
