### PR TITLE
configurable service working directory

### PR DESCRIPTION
**Pull request by webarchymeta**
allow specifying service working directory using config option "cwd"

### CODE REVIEW

**Comment by jdziat** [comment]
This is already possible though via the workingDirectory option. Unless I'm missing something.

**Comment by webarchymeta** [comment]
You can't set `workingDirectory` in the config parameter of the constructor of service at present, this PR tries the make it possible. I used a short handed name `cwd` for it in the config object since I also used the same name in the linux version. Perhaps it would be more consistent to use the name `workingDirectory` for it in the config object for consistency ...

**Comment by jdziat** [comment]
I believe it’s called workingdirectory. Look at lib/daemon.js. I could be missing something though.

**Comment by webarchymeta** [comment]
You are right, but this one doesn't seem to be consistent with naming of other properties

**Comment by jdziat** [comment]
You’re not wrong but it may have more todo with keeping compatibility with the other node-{os} packages. I’ll have to look into the other packages.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdziat** [comment]
I’m going to close this as it’s already been enabled. However we do need to review the other codebases and make sure we’re being consistent across all the packages.

**Comment by JoseIgnacio92** [comment]
https://github.com/coreybutler/node-windows/issues/225

**Pull request closed without merging**
